### ISSUE TITLE
Much redundant code at the models

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/install-from-web-server#15]
Hi we have very much redundant code at the frontend models:
https://github.com/joomla-extensions/install-from-web-server/tree/master/components/com_apps/models

All models  extends `JModelList` and not `AppsModelBase` is there any reason to do so?

https://github.com/joomla-extensions/install-from-web-server/blob/master/components/com_apps/models/category.php#L19

**Comment by nicksavov** [comment]
Yes, lots of duplication in the models that needs to be cleaned up.

**Comment by zero-24** [comment]
Ok i will send a PR if we get the others in ;) Thanks.
