### ISSUE TITLE
Core Hack for the update file?

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/install-from-web-server#16]
Do we have any real reason to `hack` into the core files?

https://github.com/joomla-extensions/install-from-web-server/blob/master/components/com_apps/models/extension.php#L201-211

```php
$updatefile = JPATH_ROOT . '/libraries/joomla/updater/update.php';
$fh = fopen($updatefile, 'r');
$theData = fread($fh, filesize($updatefile));
fclose($fh);
$theData = str_replace('<?php', '', $theData);
$theData = str_replace('$ver->PRODUCT', "'".$product."'", $theData);
$theData = str_replace('$ver->RELEASE', "'".$release."'", $theData);
$theData = str_replace('$ver->DEV_LEVEL', "'".$dev_level."'", $theData);
eval($theData);
```

**Comment by wilsonge** [comment]
Well the reason why is that you need to pass into the XML update file the version of Joomla that the user has - not the Install from Web Server Joomla version. Having said that it's definitely something we should look to improve
