### ISSUE TITLE
[staging server] Issue with images still exists

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/install-from-web-server#17]
Please see:
![to_big_images_jed](https://cloud.githubusercontent.com/assets/2596554/6427929/b354291c-bf8f-11e4-97b1-c517f3438b16.PNG)

**Comment by nicksavov** [comment]
It doesn't look like it's loading https://github.com/joomla-extensions/install-from-web-server/blob/master/components/com_apps/css/apps.css at all

**Comment by nicksavov** [comment]
Tobias found https://github.com/joomla-extensions/install-from-web-server/commit/e66e9c60c986318ce317b5fb4cf897b8fc59814b . Anyone know the reason for that change? Should we try putting styling on the client side?

**Comment by zero-24** [comment]
Closing as this is fixed with #21 Thanks @nicksavov
