### ISSUE TITLE
[staging server] Search don't work with extensions that contains spaces

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/install-from-web-server#18]
The search don't work with extensions that contains spaces

- try to seach a extension like `ACL Manager`

**Comment by zero-24** [comment]
oops wrong image:
![acl_manager_jed](https://cloud.githubusercontent.com/assets/2596554/6427948/83426e4a-bf90-11e4-9bfa-bed3bbc0d0dc.PNG)

**Comment by nicksavov** [comment]
Same here
