### ISSUE TITLE
[staging server] Sort by name dont work as expected

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/install-from-web-server#19]
As for Sort by name i would explect to have listings stating with `A` to be the first but we have a extension that calls `Encrypted Contact Form for Joomla!` as first entry

![sort_by_name_jed](https://cloud.githubusercontent.com/assets/2596554/6427970/4372cc8c-bf91-11e4-8a96-3f088c7e6b7f.PNG)

**Comment by nicksavov** [comment]
Looks like it's working (for example, try in some of the categories), but in the Home area it's loading all the extension and the top 6 have something weird in the name that's causing them to appear first (before the other names starting with parenthesis, numbers, or letters).

**Comment by nicksavov** [comment]
Checkout the page source at http://extensions.joomla.org/index.php?option=com_jed&view=extension&layout=default&id=9437 and there's a space at the start of the title. Same for http://extensions.joomla.org/index.php?option=com_jed&view=extension&layout=default&id=9157

Thus, looks like it's working as expected and a bug on the JED end.

**Comment by zero-24** [comment]
Closing as a issue on the JED site (space bevor the name) Thanks @nicksavov
