### ISSUE TITLE
Show Stoppers

### ISSUE THREAD

**Issue by nicksavov** [joomla-extensions/install-from-web-server#23]
https://github.com/joomla-extensions/install-from-web-server/pull/20/
https://github.com/joomla-extensions/install-from-web-server/pull/21
https://github.com/joomla-extensions/install-from-web-server/pull/22 (fixes https://github.com/joomla-extensions/install-from-web-server/issues/18)

Once the above are reviewed and merged, the staging server should be updated with latest master for final testing.

**Comment by losedk** [comment]
I would like to test. Am I able to bypass the warning from the callback, so I can test?

**Comment by zero-24** [comment]
@losedk can you add me on skype? (zero24__) Than i can help you to test.

**Comment by losedk** [comment]
@zero-24 done!

**Comment by nicksavov** [comment]
Thanks @losedk!

#20 is resolved.
#22 is resolved.

#21 is closed in favor of https://github.com/joomla-extensions/install-from-web-client/pull/20

**Comment by nicksavov** [comment]
One more: https://github.com/joomla-extensions/install-from-web-server/pull/26

**Comment by losedk** [comment]
Did we solve all the show stoppers?

**Comment by beat** [comment]
#26 is resolved.

So, yes.

Will be uploading to staging next hours, then if all ok in tests we will reactivate live in very next days!

:+1: Many Thanks to all who helped !

So guess can close this (can be reopened if we see a roadblocker).

**Comment by losedk** [comment]
Great! :)

**Comment by nicksavov** [comment]
Nice work, guys! :)

**Comment by beat** [comment]
Sorry to re-open already with #27 , but that's what staging is for.

**Comment by beat** [comment]
(Forgot to mention that Staging is now updated with latest).

Hope someone has time to jump in and can fix this over the week-end ?

**Comment by beat** [comment]
Closing as all show-stoppers are resolved and "Install from Web" is now online again with JED 3.

Thanks all for reporting, triaging, fixing and testing !

We still have open issues to resolve, but no show-stoppers.
