### ISSUE TITLE
We need downsampled (cached) images from JED server instead of full-sized ones

### ISSUE THREAD

**Issue by beat** [joomla-extensions/install-from-web-server#27]
All images are full-size, instead of downsampled, some of them up to almost 1 megabyte.

Our "Home" page is 45+ Megabytes, which on a fast 10 Mbits/s Internet connection uses around 40 seconds to load. Even on a very fast 100 Mbits/s Internet-connection, it takes 10-15 seconds to load and render, even through the CDN near you.

For category views at very least, we need to get/use downsampled images, like available on JED's server uses them itself, e.g.

http://extensionscdn.joomla.org/cache/fab_image/54951d688f158_resizeDown302px133px16.jpg

Sorry, I'm categorizing this issue as a show-stopper, as a lot of people are below 1 Mbits/s, so Home would take over 5 minutes to load !

**Comment by nicksavov** [comment]
Hi Beat,

I might be mistaken, but it doesn't look like there's an API entry point into the resizeDown images, so I've submitted the following str_replace / substr_replace PR for it:
https://github.com/joomla-extensions/install-from-web-server/pull/28

Alternatively, preg_replace() could be used to do it as a regular expression in one statement. I'm not sure which would be better performance wise, but I'm guessing the difference is negligible.

**Comment by nicksavov** [comment]
Here's the regex one: https://github.com/joomla-extensions/install-from-web-server/pull/29

**Comment by nicksavov** [comment]
One more: https://github.com/joomla-extensions/install-from-web-server/pull/30

**Comment by beat** [comment]
#29 and #30 merged (#28 closed)
