### ISSUE TITLE
a11y and multilingual todo

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/install-from-web-server#38]
https://github.com/joomla-extensions/install-from-web-server/blob/433aedaa0d2cba14dd6ad41aa9912392762f1477/components/com_apps/layouts/apps/j4/simple_search.php#L38

Need to change this to be accessible and to be translatable

**Comment by mbabker** [comment]
We need to pass the language code forward from the CMS install so that the rendered markup can be properly translated (and maybe actually rendered in RTL properly, right now the entire server operates in en-GB).

**Comment by mbabker** [comment]
Just pushed https://github.com/joomla-extensions/install-from-web-server/commit/4607bc9b9e1656e741db84afe98d10a6f054b69d which should handle changing the language over to the client language.  So, should be able to do a cleanup on the language strings, make sure there isn't hardcoded text, and get things set up for translations soon.
