### ISSUE TITLE
Sub categories class

### ISSUE THREAD

**Issue by brianteeman** [joomla-extensions/install-from-web-server#42]
Can you add a class on the subcategories in the j4 sidebar children please to make it ewasier to indent with css

**Comment by mbabker** [comment]
I just pushed https://github.com/joomla/joomla-cms/commit/0329fa71c63d772c4e355d8fe659af05f521d4a9 to the main repo, is that enough?

**Comment by brianteeman** [comment]
lol - i was just coming back to close this as I had done it in the css
