### ISSUE TITLE
Update to current CMS version

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/install-from-web-server#5]
The code in the repository here indicates the server hasn't been updated since shortly after 3.2's release 14 months ago.  Please update the server to the current version.

**Comment by beat** [comment]
@mbabker We are not using the Joomla from this repository, but an independant Joomla installation, which is kept with all relevant security-updates, and onto which the component-relevant folders are installed. We could actually remove the standard Joomla-code from this repository. Separate PR welcome.

Closing this issue, as non-issue. :-)

**Comment by Bakual** [comment]
>  an independant Joomla installation, which is kept with all relevant security-updates

@beat Does this mean you have manually applied security fixes? Or does that mean it's running a regular 3.3.6? If it's not a regular 3.3.6, why not? Core hacks?

**Comment by beat** [comment]
@Bakual Hi Thomas! All security updates that are relevant or that server have been applied readily and additional security measures have been taken when installing the server through server configurations. The server runs Joomla, but without most of the items found on a regular Joomla web-content server, and is thus much less subject to attack vectors. It has latest Joomla installed right now. Remember that I'm also in the JSST and follow closely all Joomla relevant security information and updates, and would update that server most probably even ahead of a security release if a critical security issue that affects that server in its use of Joomla would have appeared or would appear. BTW Sorry for the bit slow answer here, but I have seen your question same day, and, if it would have had any security-relevant issues, I would have addressed it immediately.

**Comment by ot2sen** [comment]
This "unique setup" should be documented in details for the PLT.

It sound like a major busfactor having a non-standard install running which
is directly communicating with any joomla site that decide to do so, and
only 1 or few non LT people knowing the inner details.
At minimum the PLT should know exactly how and why.

**Comment by Bakual** [comment]
@beat Thanks for taking care of the server and updating it to 3.3.6. Looks fine now to me.

**Comment by beat** [comment]
@ot2sen your quote "unique setup" is not in my reply, so please don't quote it, as it is misleading. It is a standard Joomla installation, that is taken care in a standard way, with standard-practice secure server setups. The full code of the server component is on github. No mysteries and no unique setups.

**Comment by ot2sen** [comment]
@beat My concern of the quote from me "Unique setup" had 2 parts
1. That the repo has a last date of edit from feb 2014 and says 'a year
ago' for most. Didnt sound updated.
2. Most important concern was that the PLT even had to ask. As a core
feature as the users will see this it is highly important that the
maintainers of this external feature inform the responsible PLT of any
reasons of the current broken state and obviously that the PLT has full
access. The moment the PLT have to ask as here I as a user get concerned.
The feature is broken and people ask why in the community. Old content and
linking to old ressources is a problem in many aspects. The maintainers of
this external feature should at all times keep the PLT posted and updated
so they have a real chance to evaluate if there is a chance it will get
fixed.

**Comment by beat** [comment]
@ot2sen Thanks for clarifying what you meant.

1. the "Install from web" feature has been very long very stable, and thus didn't need fix-updates appart of https support that wasn't available from the start at the hoster infrastructure.

2. Now with JED3 we have a bigger issue, and Install-from-web team-member Ashwin (@coolbung) has a public PR #4 that needs to be finished to be updated if possible in the next days ideally before or with the shortly upcoming 3.4 release. @coolbung is asking for help to get that done over next very few days. So if you (or anyone else, public call here!) have time, please get in touch with @coolbung or just work on PR #4. I'll add some instructions on PR #4 for help now. Would be really appreciated. My free time has unfortunately come to a crawl, and while I can still help to manage, I'll probably not be able to help in coding over the next few days.

3. At least one, sometimes more PLT members have always been part of the Install-from-web team, which has a skype group chat, so I don't think that the problem you are referring to is a real problem of the install-from-web team. Maybe it is an internal communication issue, but please stop blaming the Install-from-web team. If you wish to help, get active on PR #4 and ask a PLT member to add you to the chat (@Bakual is in it now). I have no issues discussing things positively publicly, as long as there is also helping involved. As usual "Contributions warmly welcome", "heads-up" too, but only if followed by help to fix.

Back to work on #4 .
